/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("nadinenathaniel.kotlin-application-conventions")
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)

    implementation(libs.kord.extensions)
    implementation(libs.okhttp)

    implementation(libs.slf4j.api)
    implementation(libs.logback.core)
    implementation(libs.logback.classic)
    implementation(libs.kotlin.logging.jvm)

    implementation(libs.sqldelight.drivers.jdbc)
    implementation(libs.sqldelight.coroutines)
    implementation(libs.hikaricp)
    implementation(libs.postgresql)

    implementation(libs.kotlinx.serialization.hocon)

    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)

    implementation(projects.data)
    implementation(projects.parsers)
    implementation(projects.kordexExtensions)
}

application {
    // Define the main class for the application.
    mainClass.set("nadinenathaniel.app.AppKt")
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to application.mainClass
        )
    }
}
